version: '3'
services:
  web:
    build:
      context: ./Docker
      dockerfile: ./web/Dockerfile
    volumes:
      - ./Docker/web:/app
    ports:
      - "8000:8000"
    environment:
      TZ: "Asia/Tokyo"
      DB_HOST: db
      DB_USER: root
      DB_PASS: mysql_pass
      DB_NAME: web_logs
    depends_on:
      - db
  db:
    image: mysql:5.7
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: mysql_pass
      MYSQL_DATABASE: web_logs
    ports:
      - "3307:3306"
